#!/bin/sh

## valid options are "UEFI" or "BIOS"
GRUB="UEFI"

TARGET="/dev/sda4"
EFI="/dev/sda1"
SWAP="/dev/sda2"

#GRUB="BIOS"

#TARGET="/dev/sda3"
#SWAP="/dev/sda1"
#HOME="/dev/sda4"

ROOT="/mnt/steamos"

USERNAME="hitsuji"
PASSWORD="hitsuji"
