#!/bin/sh

. /usr/share/debconf/confmodule

# prevent lightdm config from forcing the display-manager dialog
OWNERS=
if db_metaget shared/default-x-display-manager owners; then
  OWNERS="$RET"
fi

db_subst shared/default-x-display-manager choices "$OWNERS"
